app:
  scheduling:
    clean-user-expired-sessions:
      cron: 0 0 3 * * ?
      run-duration: 2h
      clean-from-days-before: 30

#  message:
#    redis:
#      # 启用redis消息
#      enabled: true
#      namespace: ${spring.application.name}
#    pulsar:
#      # 本应用所需的pulsar注册信息
#      base-reg:
#        tenant: starry
#        namespace: ${spring.application.name}

  security:
    enable-front-back-seperated: true
    namespace-prefix: ${spring.application.name}

    # 非Ajax方式登录成功后，默认重定向到由前端提供的后台功能页面
    default-login-success-target-url: http://127.0.0.1:7080/admin

    oauth2:
      client:
        # 是否开启OAuth2客户端登录
        enable: true

        # OAuth2客户端的注册配置列表
        registration:
          oidc-client:
            provider: spring
            client-id: oidc-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/oidc-client
            scope: openid,profile
            client-name: Spring
          github:
            provider: github
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/github
            scope: read:user
            client-name: GitHub

        # 授权服务器提供者配置列表
        provider:
          spring:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

mybatis:
  mapper-locations: classpath*:mapper/*.xml

# RocketMQ配置
rocketmq:
  # 单机部署
  # name-server: ${app.middleware-host}:9876
  # 集群部署
  name-server: ${app.middleware-host}:9876;${app.middleware-host}:9886;${app.middleware-host}:9896
  producer:
    group: ${spring.application.name}
    namespace: ${spring.application.name}

spring:
  # DataSource
  datasource:
    username: root
    password: ''
    url: jdbc:mysql://${app.middleware-host}/authorization_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    hikari:
      minimum-idle: 50
      maximum-pool-size: 150
      connection-test-query: SELECT 1

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    # Redis
    redis:
      database: 0
      password: '123456'
      # 单机配置
#      host: ${app.middleware-host}
#      port: 6379

      # sentinel配置
#      sentinel:
#        master: mymaster
#        nodes:
#          - ${app.middleware-host}:26379
#          - ${app.middleware-host}:26380
#          - ${app.middleware-host}:26381

      # 集群配置
      cluster:
        nodes: ${app.middleware-host}:6379,${app.middleware-host}:6380,${app.middleware-host}:6381,${app.middleware-host}:6382,${app.middleware-host}:6383,${app.middleware-host}:6384
        max-redirects: 3
      lettuce:
        pool:
          max-active: 300
          max-idle: 200
          min-idle: 50
          max-wait: 5000ms
      timeout: 3000ms

  # Pulsar配置
  #  pulsar:
  #    client:
  #      service-url: pulsar://${app.middleware-host}:6650
  #    admin:
  #      service-url: http://${app.middleware-host}:8080

  # ES
  elasticsearch:
    uris: http://${app.middleware-host}:9200

  # springboot启用虚拟线程
  threads:
    virtual:
      enabled: true

  main:
    # 启用虚拟线程后，由于虚拟线程都是守护线程，为防止JVM因没有非守护线程而自动退出，需要设置此值为true
    #（参考：https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.virtual-threads）
    keep-alive: true
    # 允许Spring循环依赖
    allow-circular-references: true
