spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    openai:
      api-key: "XXX"
      base-url: "https://api.siliconflow.cn"
      audio:
        transcription:
          model: "TeleAI/TeleSpeechASR"
        speech:
          model: "fnlp/MOSS-TTSD-v0.5"
          voice: "fnlp/MOSS-TTSD-v0.5:claire"
          response-format: mp3
          speed: 0.75
      chat:
        model: "Qwen/Qwen3.5-4B"
        api-key: "XXX"
      embedding:
        model: "BAAI/bge-m3"
    mcp:
      client:
        type: SYNC
        streamable-http:
          connections:
            starry:
              url: http://127.0.0.1:8090
        # 启动应用时，不要执行mcp客户端的初始化，防止mcp服务不可用时导致本应用无法启动
        initialized: false
#    vectorstore:
#      milvus:
#        auto-id: true
#        client:
#          host: ${app.middleware-host}
#          port: 19530
#        collection-name: "dev"
#        database-name: "starry"
##        initialize-schema: true
#        embedding-dimension: 1024

#  datasource:
#    # 此数据源用于实现jdbc聊天记忆
#    username: root
#    password: ''
#    url: jdbc:mysql://${app.middleware-host}/authorization_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
#    hikari:
#      minimum-idle: 50
#      maximum-pool-size: 150
#      connection-test-query: SELECT 1

app:
  ai:
    vectorstore:
      elasticsearch:
        index-name: starry-rag
        similarity: cosine
        dimensions: 1024
        embedding-field-name: embedding
        initialize-schema: false
