logging:
  pattern:
    console: "[%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%level){blue} %clr([%X{starry-traceId}]){yellow} %clr([%thread]){orange} %clr(%logger){cyan}%clr([%L]){yellow} %m%n}"

spring:
  ai:
    openai:
      api-key: "XXX"
      base-url: "XXX"
      audio:
        transcription:
          options:
            model: "XXX"
      chat:
        api-key: "XXX"
        base-url: "XXX"
        completions-path: "XXX"
        options:
          model: "XXX"
    mcp:
      client:
        type: SYNC
        sse:
          connections:
            starry:
              url: http://127.0.0.1:8090
        # 启动应用时，不要执行mcp客户端的初始化，防止mcp服务不可用时导致本应用无法启动
        initialized: false
