package com.walter.starry.security.base.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   用户表OIDC表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table users_oidc
 */
public class AclUserOidc implements Serializable {
    /**
     * Database Column Remarks:
     *   物理主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_oidc.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_oidc.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   OAuth2授权服务器的在本应用内的OIDC注册ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_oidc.oidc_registration_id
     *
     * @mbg.generated
     */
    private String oidcRegistrationId;

    /**
     * Database Column Remarks:
     *   用户在OAuth2授权服务器中的开放账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_oidc.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_oidc.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_oidc.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_oidc.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_oidc.id
     *
     * @return the value of users_oidc.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_oidc.id
     *
     * @param id the value for users_oidc.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_oidc.username
     *
     * @return the value of users_oidc.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_oidc.username
     *
     * @param username the value for users_oidc.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_oidc.oidc_registration_id
     *
     * @return the value of users_oidc.oidc_registration_id
     *
     * @mbg.generated
     */
    public String getOidcRegistrationId() {
        return oidcRegistrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_oidc.oidc_registration_id
     *
     * @param oidcRegistrationId the value for users_oidc.oidc_registration_id
     *
     * @mbg.generated
     */
    public void setOidcRegistrationId(String oidcRegistrationId) {
        this.oidcRegistrationId = oidcRegistrationId == null ? null : oidcRegistrationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_oidc.open_id
     *
     * @return the value of users_oidc.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_oidc.open_id
     *
     * @param openId the value for users_oidc.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_oidc.enabled
     *
     * @return the value of users_oidc.enabled
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_oidc.enabled
     *
     * @param enabled the value for users_oidc.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_oidc.create_time
     *
     * @return the value of users_oidc.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_oidc.create_time
     *
     * @param createTime the value for users_oidc.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_oidc.update_time
     *
     * @return the value of users_oidc.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_oidc.update_time
     *
     * @param updateTime the value for users_oidc.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}