package com.walter.starry.security.base.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table users
 */
public class AclUser implements Serializable {
    /**
     * Database Column Remarks:
     *   物理主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     * Database Column Remarks:
     *   账号是否已过期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account_expired
     *
     * @mbg.generated
     */
    private Boolean accountExpired;

    /**
     * Database Column Remarks:
     *   账号是否已被锁
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account_locked
     *
     * @mbg.generated
     */
    private Boolean accountLocked;

    /**
     * Database Column Remarks:
     *   密码是否已过期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.credentials_expired
     *
     * @mbg.generated
     */
    private Boolean credentialsExpired;

    /**
     * Database Column Remarks:
     *   清理失效会话集时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.expired_sessions_clean_time
     *
     * @mbg.generated
     */
    private Date expiredSessionsCleanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nickname
     *
     * @return the value of users.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nickname
     *
     * @param nickname the value for users.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.enabled
     *
     * @return the value of users.enabled
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.enabled
     *
     * @param enabled the value for users.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account_expired
     *
     * @return the value of users.account_expired
     *
     * @mbg.generated
     */
    public Boolean getAccountExpired() {
        return accountExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account_expired
     *
     * @param accountExpired the value for users.account_expired
     *
     * @mbg.generated
     */
    public void setAccountExpired(Boolean accountExpired) {
        this.accountExpired = accountExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account_locked
     *
     * @return the value of users.account_locked
     *
     * @mbg.generated
     */
    public Boolean getAccountLocked() {
        return accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account_locked
     *
     * @param accountLocked the value for users.account_locked
     *
     * @mbg.generated
     */
    public void setAccountLocked(Boolean accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.credentials_expired
     *
     * @return the value of users.credentials_expired
     *
     * @mbg.generated
     */
    public Boolean getCredentialsExpired() {
        return credentialsExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.credentials_expired
     *
     * @param credentialsExpired the value for users.credentials_expired
     *
     * @mbg.generated
     */
    public void setCredentialsExpired(Boolean credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.expired_sessions_clean_time
     *
     * @return the value of users.expired_sessions_clean_time
     *
     * @mbg.generated
     */
    public Date getExpiredSessionsCleanTime() {
        return expiredSessionsCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.expired_sessions_clean_time
     *
     * @param expiredSessionsCleanTime the value for users.expired_sessions_clean_time
     *
     * @mbg.generated
     */
    public void setExpiredSessionsCleanTime(Date expiredSessionsCleanTime) {
        this.expiredSessionsCleanTime = expiredSessionsCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_time
     *
     * @return the value of users.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_time
     *
     * @param createTime the value for users.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.update_time
     *
     * @return the value of users.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.update_time
     *
     * @param updateTime the value for users.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}