<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.walter.starry</groupId>
		<artifactId>authorization-server-parent</artifactId>
		<version>0.0.1</version>
		<relativePath>../pom.xml</relativePath> <!-- lookup parent from repository -->
	</parent>
	<artifactId>authorization-server-spring-boot-autoconfigure</artifactId>
	<version>0.0.1</version>
	<name>authorization-server-spring-boot-autoconfigure</name>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-authorization-server</artifactId>
		</dependency>
		<dependency>
			<groupId>com.walter.starry</groupId>
			<artifactId>security-spring-boot-autoconfigure</artifactId>
		</dependency>
	</dependencies>
</project>
