services:
  rmq-namesrv:
    image: apache/rocketmq:5.3.3
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/rocketmq/namesrv/logs:/home/rocketmq/logs
    environment:
      HEAP_OPTS: -Xms128m -Xmx128m -Xmn64m
    networks:
      starry:
        ipv4_address: 172.18.3.1
    command: sh mqnamesrv
  rmq-broker:
    image: apache/rocketmq:5.3.3
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/rocketmq/broker/conf/broker.conf:/home/rocketmq/conf/broker.conf
      - ./data/rocketmq/broker/logs:/home/rocketmq/logs
      - ./data/rocketmq/broker/store:/home/rocketmq/store
    environment:
      NAMESRV_ADDR: rmqnamesrv:9876
      HEAP_OPTS: -Xms256m -Xmx256m -Xmn128m -XX:MaxDirectMemorySize=128m
    depends_on:
      - rmq-namesrv
    networks:
      starry:
        ipv4_address: 172.18.3.2
    command: ["sh","mqbroker","-c","/home/rocketmq/conf/broker.conf"]
  rmq-proxy:
    image: apache/rocketmq:5.3.3
    container_name: rmqproxy
    networks:
      starry:
        ipv4_address: 172.18.3.3
    depends_on:
      - rmq-broker
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./data/rocketmq/proxy/logs:/home/rocketmq/logs
      - ./data/rocketmq/proxy/.rocketmq_offsets:/home/rocketmq/.rocketmq_offsets
    restart: on-failure
    environment:
      NAMESRV_ADDR: rmqnamesrv:9876
      HEAP_OPTS: -Xms128m -Xmx128m -Xmn64m
    command: sh mqproxy
  rmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:2.0.1
    container_name: rmqdashboard
    ports:
      - 18080:8080
    networks:
      starry:
        ipv4_address: 172.18.3.4
    restart: always
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Xms128m -Xmx128m -Xmn64m"
    depends_on:
      - rmq-proxy
