services:
  rmq-namesrv:
    image: apache/rocketmq:5.3.3
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      starry:
        ipv4_address: 172.18.3.1
    command: sh mqnamesrv
  rmq-broker:
    image: apache/rocketmq:5.3.3
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - rmq-namesrv
    networks:
      starry:
        ipv4_address: 172.18.3.2
    command: sh mqbroker
  rmq-proxy:
    image: apache/rocketmq:5.3.3
    container_name: rmqproxy
    networks:
      starry:
        ipv4_address: 172.18.3.3
    depends_on:
      - rmq-broker
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy
