networks:
  starry:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

include:
    ## mysql子网网段：172.18.1.0/24
  - compose-mysql.yml
    ## redis子网网段：172.18.2.0/24
  - compose-redis.yml
    ## MQ子网网段：172.18.3.0/24
  - compose-rocketmq.yml
#  - compose-pulsar.yml
    ## minio子网网段：172.18.4.0/24
  - compose-minio.yml
    ## milvus子网网段：172.18.5.0/24
  - compose-milvus.yml
    ## APM子网网段：172.18.6.0/24
  - compose-apm.yml
