package com.walter.starry.business.app.mapper;

import com.walter.starry.business.app.entity.UserAiConversation;
import com.walter.starry.business.app.entity.UserAiConversationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserAiConversationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    long countByExample(UserAiConversationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    int deleteByExample(UserAiConversationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    int insert(UserAiConversation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    int insertSelective(UserAiConversation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    List<UserAiConversation> selectByExample(UserAiConversationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    UserAiConversation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") UserAiConversation row, @Param("example") UserAiConversationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") UserAiConversation row, @Param("example") UserAiConversationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserAiConversation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserAiConversation row);
}