app:
  version: @project.version@

logging:
  file:
    name: ./target/starry-mcp-server-app.log
  pattern:
    console: "[%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%level){blue} %clr([%X{starry-traceId}]){yellow} %clr([%thread]){orange} %clr(%logger){cyan}%clr([%L]){yellow} %m%n}"

server:
  port: 8090

spring:
  ai:
    mcp:
      server:
#        annotation-scanner:
#          enabled: true
        name: starry-mcp-server
        version: 1.0.0
#        type: SYNC
        instructions: "This server provides weather information tools and resources"
#        sse-message-endpoint: mcp/message
#        capabilities:
#          tool: true
#          resource: true
#          prompt: true
#          completion: true
        protocol: streamable
#        request-timeout: 20s
#        stdio: false
        streamable-http:
          keep-alive-interval: 30m
#          mcp-endpoint: /mcp
#        resource-change-notification: true
#        tool-change-notification: true
#        prompt-change-notification: true
  main:
    banner-mode: off
