app:
  version: @project.version@
  # 中间件所在主机（仅用于集中管理本配置文件上下文的配置，非必须）
  middleware-host: 192.168.100.42

logging:
  file:
    name: ./target/starry-mcp-server-app.log
  pattern:
    console: "[%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%level){blue} %clr([%X{starry-traceId}]){yellow} %clr([%thread]){orange} %clr(%logger){cyan}%clr([%L]){yellow} %m%n}"

server:
  port: 8090

spring:
  ai:
    mcp:
      server:
#        annotation-scanner:
#          enabled: true
        name: starry-mcp-server
        version: 1.0.0
#        type: SYNC
        instructions: "This server provides weather information tools and resources"
#        capabilities:
#          tool: true
#          resource: true
#          prompt: true
#          completion: true
        protocol: streamable
#        request-timeout: 20s
#        stdio: false
        streamable-http:
          keep-alive-interval: 30m
#          mcp-endpoint: /mcp
#        resource-change-notification: true
#        tool-change-notification: true
#        prompt-change-notification: true

  # DataSource
  datasource:
    username: root
    password: ''
    url: jdbc:mysql://${app.middleware-host}/authorization_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    hikari:
      minimum-idle: 50
      maximum-pool-size: 150
      connection-test-query: SELECT 1

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  main:
    banner-mode: off
