package com.walter.starry.security.base.mapper;

import com.walter.starry.security.base.entity.AclUserOidc;
import com.walter.starry.security.base.entity.example.AclUserOidcExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AclUserOidcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    long countByExample(AclUserOidcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    int deleteByExample(AclUserOidcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    int insert(AclUserOidc row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    int insertSelective(AclUserOidc row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    List<AclUserOidc> selectByExample(AclUserOidcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    AclUserOidc selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AclUserOidc row, @Param("example") AclUserOidcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AclUserOidc row, @Param("example") AclUserOidcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AclUserOidc row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_oidc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AclUserOidc row);
}