app:
  # 中间件所在主机（仅用于集中管理本配置文件上下文的配置，非必须）
  middleware-host: 192.168.100.42

server:
  port: 9000
  shutdown: graceful

spring:
  application:
    name: starry-authorization-server-app

  config:
    import: classpath:application-security.yml

  # 优雅停机的宽限期
  lifecycle:
    timeout-per-shutdown-phase: 120s

logging:
  pattern:
    console: "[%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%level){blue} %clr([%X{starry-traceId}]){yellow} %clr([%thread]){orange} %clr(%logger){cyan}%clr([%L]){yellow} %m%n}"
#  level:
#    org.springframework.security: trace

management:
  endpoints:
    web:
      exposure:
        # 暴露health端点，可供Nginx或容器探针进行健康检查，实现无损上下线
        #        include: "health"
        include: "*"