app:
  # 中间件所在主机（仅用于集中管理本配置文件上下文的配置，非必须）
  middleware-host: 192.168.10.235

  scheduling:
    clean-user-expired-sessions:
      cron: 0 0 3 * * ?
      run-duration: 2h
      clean-from-days-before: 30

  pulsar:
    base-reg:
      tenant: starry
      namespace: ${spring.application.name}

  security:
    enable-front-back-seperated: true
    namespace-prefix: AuthorizationServer

    # 非Ajax方式登录成功后，默认重定向到由前端提供的后台功能页面
    default-login-success-target-url: http://localhost:7080/admin

    oauth2:
      client:
        # 是否开启OAuth2客户端登录
        enable: false

logging:
  pattern:
    console: "[%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%level){blue} %clr([%X{traceId}]){yellow} %clr([%thread]){orange} %clr(%logger){cyan}%clr([%L]){yellow} %m%n}"
  level:
    org.springframework.security: trace

server:
  port: 9000
  shutdown: graceful

spring:
  application:
    name: authorization-server-app

  # DataSource
  datasource:
    username: root
    password: ''
    url: jdbc:mysql://localhost/authorization_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    hikari:
      minimum-idle: 50
      maximum-pool-size: 150
      connection-test-query: SELECT 1

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    # Redis
    redis:
      host: ${app.middleware-host}
      port: 6379
      database: 0
      password: ''
      lettuce:
        pool:
          max-active: 300
          max-idle: 200
          min-idle: 50
          max-wait: 5000ms
      timeout: 3000ms

  # Pulsar配置
  pulsar:
    client:
      service-url: pulsar://${app.middleware-host}:6650
    admin:
      service-url: http://${app.middleware-host}:8080

  # ES
  elasticsearch:
    uris: http://127.0.0.1:9203, http://127.0.0.1:9204, http://127.0.0.1:9205

  # springboot启用虚拟线程
  threads:
    virtual:
      enabled: true

  main:
    # 启用虚拟线程后，由于虚拟线程都是守护线程，为防止JVM因没有非守护线程而自动退出，需要设置此值为true
    #（参考：https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.virtual-threads）
    keep-alive: true
    # 允许Spring循环依赖
    allow-circular-references: true

  # 优雅停机的宽限期
  lifecycle:
    timeout-per-shutdown-phase: 120s