services:
  redis-master:
    image: redis:8.2.7
    container_name: redis-master
    hostname: redis-master
    volumes:
      - ./data/redis/sentinel/master/conf:/usr/local/etc/redis
      - ./data/redis/sentinel/master/data:/data
    command: bash -c "redis-server /usr/local/etc/redis/redis.conf --port 6379"
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 6379 -a 123456 ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.20'

  redis-slave1:
    image: redis:8.2.7
    container_name: redis-slave1
    hostname: redis-slave1
    volumes:
      - ./data/redis/sentinel/slave1/conf:/usr/local/etc/redis
      - ./data/redis/sentinel/slave1/data:/data
    command: bash -c "redis-server /usr/local/etc/redis/redis.conf --port 6380 --replicaof ${DOCKER_HOST} 6379"
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 6380 -a 123456 ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      redis-master:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.20'

  redis-slave2:
    image: redis:8.2.7
    container_name: redis-slave2
    hostname: redis-slave2
    volumes:
      - ./data/redis/sentinel/slave2/conf:/usr/local/etc/redis
      - ./data/redis/sentinel/slave2/data:/data
    command: bash -c "redis-server /usr/local/etc/redis/redis.conf --port 6381 --replicaof ${DOCKER_HOST} 6379"
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 6380 -a 123456 ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      redis-master:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.20'

  redis-sentinel-1:
    image: redis:8.2.7
    container_name: redis-sentinel-1
    hostname: redis-sentinel-1
    volumes:
      - ./data/redis/sentinel/stl1:/usr/local/etc/redis
     # 首次部署时，指定mymaster的主节点，后续启动时无需指定了（配置文件已被自动rewrite）
#    command: bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26379 --sentinel monitor mymaster ${DOCKER_HOST} 6379 2"
    command: bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26379"
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 26379 ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave1:
        condition: service_healthy
      redis-slave2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.20'

  redis-sentinel-2:
    image: redis:8.2.7
    container_name: redis-sentinel-2
    hostname: redis-sentinel-2
    volumes:
      - ./data/redis/sentinel/stl2:/usr/local/etc/redis
     # 首次部署时，指定mymaster的主节点，后续启动时无需指定了（配置文件已被自动rewrite）
#    command: bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26380 --sentinel monitor mymaster ${DOCKER_HOST} 6379 2"
    command: bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26380"
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 26380 ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave1:
        condition: service_healthy
      redis-slave2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.20'

  redis-sentinel-3:
    image: redis:8.2.7
    container_name: redis-sentinel-3
    hostname: redis-sentinel-3
    volumes:
      - ./data/redis/sentinel/stl3:/usr/local/etc/redis
     # 首次部署时，指定mymaster的主节点，后续启动时无需指定了（配置文件已被自动rewrite）
#    command: bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26381 --sentinel monitor mymaster ${DOCKER_HOST} 6379 2"
    command: bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf --port 26381"
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 26381 ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave1:
        condition: service_healthy
      redis-slave2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.20'