package com.walter.starry.business.app.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   用户对话AI的关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_ai_conversation
 */
public class UserAiConversation implements Serializable {
    /**
     * Database Column Remarks:
     *   物理主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ai_conversation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ai_conversation.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   对话ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ai_conversation.conversation_id
     *
     * @mbg.generated
     */
    private Long conversationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ai_conversation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ai_conversation.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_ai_conversation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ai_conversation.id
     *
     * @return the value of user_ai_conversation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ai_conversation.id
     *
     * @param id the value for user_ai_conversation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ai_conversation.username
     *
     * @return the value of user_ai_conversation.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ai_conversation.username
     *
     * @param username the value for user_ai_conversation.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ai_conversation.conversation_id
     *
     * @return the value of user_ai_conversation.conversation_id
     *
     * @mbg.generated
     */
    public Long getConversationId() {
        return conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ai_conversation.conversation_id
     *
     * @param conversationId the value for user_ai_conversation.conversation_id
     *
     * @mbg.generated
     */
    public void setConversationId(Long conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ai_conversation.create_time
     *
     * @return the value of user_ai_conversation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ai_conversation.create_time
     *
     * @param createTime the value for user_ai_conversation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ai_conversation.update_time
     *
     * @return the value of user_ai_conversation.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ai_conversation.update_time
     *
     * @param updateTime the value for user_ai_conversation.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}